#!/bin/zsh
# vim: filetype=sh
grep -v "#" ~/.config/misc/emoji \
	| dmenu -i -l 20  -fn "Fira Code-17" \
	| awk '{print $1}' \
	| tr -d '\n' \
	| xclip -selection clipboard
[ ! -z "$(xclip -o -selection clipboard)" ] && pgrep -x dunst > /dev/null && notify-send "$(xclip -o -selection clipboard) copied to your clipboard !" 
