#!/bin/env sh
#----------------------------------------------------------
# MPT: ~o(( a script to watch youtube videos using mpv ))o~
#----------------------------------------------------------
# mpv uses directly the best video quality that a particular youtube video provides to play
# this script helps you to select the quality you want

#TODO: don't process a link that its already in the queue
## use --batch-file  
#TODO: audio only option
#TODO: better dmenu interface
#TODO: if the link was from invidious.snopyta.org, substitute it with youtube.com
#INFO
VERSION=0.9

link="${1:-$(xclip -o -selection clipboard)}" && notify-send "  Loading Video..."
# create a tempfile and store the video quality and codes in it
_twitch(){
    vid_quality=$(echo '160p\n360p\n480p\n720p60\n1080p60' \
        | dmenu -l 20 -fn FantasqueSansMono-13 -p " Select video quality:") 

    mpv --ytdl-format="$vid_quality" "$link" \
    || notify-send ' error occured'

}
_youtube(){
    vid_info="$( youtube-dl -F ${link} )"
    maxfilesize=2048
    vid_log_file=${XDG_CACHE_HOME}/mpt.log
    
    # Extract the sound code
    snd_code=$(echo "${vid_info}" \
    	       | awk '/audio only/{print $1" "$NF}' \
    	| sort -n -k2 \
    	| head -1 \
    	| awk '{print $1}')
    # prompt me for video resolutions available, then extract its code
    vid_code=$(echo "${vid_info}" \
    	       | awk '/video only/{print $1" "$3" "$NF}' \
    	| sort -n -k3 \
    	| sort -nu -k2 \
    	|  dmenu -l 20 -fn FantasqueSansMono-13 -p " Select video quality:" \
    	| awk '{print $1}')
    
    
    # combine the two format and play them in realtime
    setsid mpv --ytdl-raw-options=format="$vid_code"+"$snd_code" ${link} 
    
    #      LOGGING
    
    # Extract video title
    vid_title="$( youtube-dl --get-title ${link} )"
    # log the video's link into ~/.cache/mpt.log, before the video starts 
    echo "[$(date '+%F_%T')]:${link},${vid_title}" >> ${vid_log_file}

}
audio(){
vid_info="$( youtube-dl -F ${link} )"
maxfilesize=2048
vid_log_file=${XDG_CACHE_HOME}/mpt.log

# Extract the sound code
snd_code=$(echo "${vid_info}" \
	       | awk '/audio only/{print $1" "$NF}' \
	| sort -n -k2 \
	| head -1 \
	| awk '{print $1}')
setsid mpv --ytdl-raw-options=format="$snd_code" ${link} 

}
main(){
    [ ! -z $link ] && echo $link | grep "twitch" && _twitch || _youtube
}
usage(){
    echo "
mpt [OPTION] [LINK]

OPTION:
    -v    print version
    -h    print this help
LINK:
    put here a twitch or a youtube link, a list of qualities will display, choose the quality
    that suts you...ENJOY
"
}
## Extract video infos
case $1 in
    -v | --version ) echo mpt ${VERSION};;
    -h | --help ) usage ;;
    #-a | --audio) audio ;;
     * ) main ;;
esac
